Lab3
sergey-berezin/441_2_popova pull request #3
Opened 2024-11-07 14:14 UTC by polinppv

2024-11-10 16:48 UTC, sergey-berezin requested changes

2024-11-10 16:48 UTC, sergey-berezin commented on lab3/app/MainWindow.xaml.cs
> +            File.WriteAllText("../data_copy.json", old_json);
Есть метод `File.Copy`: https://learn.microsoft.com/en-us/dotnet/api/system.io.file.copy?view=net-8.0

2024-11-10 16:48 UTC, sergey-berezin commented on lab3/app/MainWindow.xaml.cs
> +            var d = new Dictionary<string, dynamic>
Проще и надежнее сделать структуры данных (POCO) со свойствами `generations`, `population`, ..., `_3x3`

2024-11-11 06:41 UTC, polinppv commented
@sergey-berezin Здравствуйте, Сергей Борисович! Исправила Ваши замечания по лабораторной работе 3 (см. commit "fix").

2024-11-11 09:24 UTC, merged